{
  reconstruction_c: {
    type: "MSE",
    weight: 1
  },
  reconstruction_s: {
    type: "MSE",
    weight: 1,
    start_weight: 0.1,
    ramp_epochs: 0,
    content_patience: 5,
    content_min_delta: 0.02,
    translation_weight: 1,
    shape_weight: 1
  },
  regularization: {
    type: "KL",
    weight: 1
  },
  thickness: {
    type: "wall_thickness",
    weight: 0
  },
  smoothness: {
    type: "laplacian",
    weight: 0,
    start_weight: 0,
    ramp_epochs: 0,
    style_patience: 5,
    style_min_delta: 0.02,
    mask_percentile: 100
  }
}
