{  
  phase_input: true,
  latent_dim: 8,
  n_features: 3,
  convolution: { 
    channels: 16 32 64 128,
    type: "Chebyshev",
    parameters: {        
      polynomial_degree: 6 6 6 6,
    }
  },
  activation_function: ReLU ReLU ReLU ReLU,
  pooling: {
    type: "quadric",
    parameters: {
      downsampling_factors: 2 2 2 2,
    }
  }
}
