seed: null

dataset: {
  data_type: "synthetic",
  cached_file: "data/cached/synthetic_population.pkl",
  preprocessing: null
}

sample_sizes: {
  training: 0.6,
  validation: 0.2,
  testing: 0.2
}

network_architecture: {
  template_mesh: "data/vedo_sphere_template.vtk",
  cached_matrices: null,
  latent_dim: 8,
  n_features: 3,
  convolution: { 
    type:"Chebyshev",
    parameters: {
      channels: 16 32 64 128,      
      polynomial_degree: 6 6 6 6,
      activation_function: relu relu relu relu,
    }
  },
  
  pooling: {
    type: "quadric",
    parameters: {
      downsampling_factors: 2 2 2 2,
    }
  }
}

loss: {
  reconstruction_loss: {
    type: "l2",
    weight: 1
  },
  regularization_loss: {
    type: "kullback_leibler_div",
    weight: 1
  }
}

optimizer: {
  algorithm: "Adam",
  parameters: {
    lr: 0.001,
    betas: [0.5, 0.99],
    weight_decay: 0.0005
  },
  batch_size: 2 
}
