seed: null

dataset: {
  data_type: "synthetic",
  parameters: {
    "amplitude_static_max": 0.3,
    "amplitude_dynamic_max": 0.1,
    "N": 5000,
    "T": 20,
    "freq_max": 3,
    "l_max": 2,
    "mesh_resolution": 12,
    "random_seed": 101
  },
  preprocessing: null
}

sample_sizes: {
  training: 0.6,
  validation: 0.2,
  testing: 0.2
}

batch_size: 32

network_architecture: {  
  phase_input: true
  latent_dim: 8,
  n_features: 3,
  convolution: { 
    channels: 16 32 64 128,
    type: "Chebyshev",
    parameters: {        
      polynomial_degree: 6 6 6 6,
    }
  },
  activation_function: ReLU ReLU ReLU ReLU,
  pooling: {
    type: "quadric",
    parameters: {
      downsampling_factors: 2 2 2 2,
    }
  }
}

loss: {
  reconstruction: {
    type: "MSE",
    weight: 1
  },
  regularization: {
    type: "KL",
    weight: 1
  }
}

optimizer: {
  algorithm: "Adam",
  parameters: {
    lr: 0.001,
    betas: [0.5, 0.99],
    weight_decay: 0.0005
  }
}

mlflow: {
  run_name: null,
  experiment_name: "Synthetic data"
 }
